### ISSUE TITLE
setSelectedContentType does not load correct tab

### ISSUE THREAD

**Issue by colorgold** [Giphy/giphy-android-sdk-ui-example#84] opened 2020-09-09 03:30 UTC
Version: com.giphy.sdk:ui:2.0

I am trying to display the Emojis first, but when I open the `giphyDialogFragment`, it shows the GIFs in the size of the emojis. 

Here is the code I used:
```
GPHSettings settings;
settings.setMediaTypeConfig(new GPHContentType[]{GPHContentType.recents,GPHContentType.emoji,GPHContentType.gif, GPHContentType.sticker, GPHContentType.text});
settings.setSelectedContentType(GPHContentType.emoji);
giphyDialogFragment = GiphyDialogFragment.Companion.newInstance(settings);
```
This is how I show the fragment:
`                giphyDialogFragment.show(chatRadioActivities.getSupportFragmentManager(), getString(R.string.giphy_dialog));
`

Here is a screenshot of what it looks like:
![emoji_load_bug](https://user-images.githubusercontent.com/45986859/92546473-3cb73d00-f218-11ea-9c42-9bc8db8ac5db.png)

**Comment by ALexanderLonsky** [comment] 2020-09-09 12:14
@colorgold thanks for flagging the issue, I'll take a look and will get back to you.

**Comment by ALexanderLonsky** [comment] 2020-09-10 16:31
@colorgold please try [v2.0.1](https://github.com/Giphy/giphy-android-sdk-ui-example/releases/tag/2.0.1)

**Comment by colorgold** [comment] 2020-09-11 00:52
@ALexanderLonsky It works! Thank you!

**Comment by colorgold** [comment] 2020-09-11 00:55
When you open the `giphyDialogFragment` for the first time, it shows up correctly. However, after that, it shows the GIFs first if not the emojis in the size of the GIFs.

**Comment by ALexanderLonsky** [comment] 2020-09-11 06:52
@colorgold I'll test this more and release a fix in the next version. I'll get back to you once it's done.

**Comment by ALexanderLonsky** [comment] 2020-09-11 10:13
@colorgold 
`However, after that, it shows the GIFs first if not the emojis in the size of the GIFs.`
does it happen when keyboard is showing up? If yes, then it's correct behaviour as we don't allow to search through emojis. I see now that grid content is not reloading when emoji was gone, this is a bug.

**Comment by colorgold** [comment] 2020-09-11 15:22
@ALexanderLonsky 
It happens without the keyboard showing up. But a bigger problem I am having is that if I try to open the keyboard, the fragment closes on its own. This is how you can reproduce the problem I am seeing:
1. Open the `giphyDialogFragment` (the emojis load correctly)
2. Close the `giphyDialogFragment` without searching for anything.
3. Open the `giphyDialogFragment` again:
     -As soon as I try to search for a GIF, the `giphyDialogFragment` closes on its own and won't let me search for anything unless I restart the activity

**Comment by ALexanderLonsky** [comment] 2020-09-11 16:27
@colorgold to my regret, I can't reproduce it..

I've updated the code for the giphy-android-sdk-ui-example example project:

```
DemoActivity.kt:

launchGiphyBtn.setOnClickListener {
            settings.mediaTypeConfig = arrayOf(
                GPHContentType.recents,
                GPHContentType.emoji,
                GPHContentType.gif,
                GPHContentType.sticker,
                GPHContentType.text
            )
            settings.selectedContentType = GPHContentType.emoji
            val dialog = GiphyDialogFragment.newInstance(settings)
            dialog.gifSelectionListener = getGifSelectionListener()
            dialog.show(supportFragmentManager, "gifs_dialog")
        }
```
updated settings with `mediaTypeConfig` and `selectedContentType`

And the fragment does not close on its own. The only issue I have now is that grid does keep its content regardless emojis visibility change. 
Did you try to run the example project? Do you have the problem there too?

Please find the video attached and correct me if I do that in the wrong way.
[video.mov.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5210364/video.mov.zip)

**Comment by ALexanderLonsky** [comment] 2020-09-11 17:38
@colorgold I've noticed that you are using Java, so I prepared a new Java project.
Please try it out too.

[test_project.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5210742/test_project.zip)

**Comment by colorgold** [comment] 2020-09-11 21:14
@ALexanderLonsky  
I tapped out the way you did, and I can go and search just fine. However, if I slide my finger downwards to close the dialog that is when I have the problem.

**Comment by ALexanderLonsky** [comment] 2020-09-12 14:16
@colorgold I can reproduce only [this one](https://github.com/Giphy/giphy-android-sdk-ui-example/issues/80) when using blur mode.

**Comment by colorgold** [comment] 2020-09-13 00:01
@ALexanderLonsky
I added `settings.setUseBlurredBackground(false);` and still the problems persists. The tab issue was fixed. It does sometimes goes back and forth between showing GIFs and emojis when opening and closing without searching anything.

Here is a video of the dialog fragment closing on its own after dismissing it by sliding down

[device-GIPHY.zip](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5213402/device-GIPHY.zip)


Here is an example where it shows the emoji as selected even though GIFs are showing:
![image](https://user-images.githubusercontent.com/45986859/93006947-40a0d300-f528-11ea-9b9b-e5169fc1c7ad.png)

Here the emojis show up in the size of GIFs after various times of opening and closing the dialog fragment
![image](https://user-images.githubusercontent.com/45986859/93006964-8067ba80-f528-11ea-90f0-918dbc17068d.png)

**Comment by ALexanderLonsky** [comment] 2020-09-14 19:11
@colorgold finally I came up with a thought you can use the same instance of `GiphyDialogFragment` and I can reproduce now the issue with the fragment is closing on its own.
As a quick solution, you can create a new instance each time you are opening it. 
You can copy the code from [here](https://github.com/Giphy/giphy-android-sdk-ui-example/files/5210742/test_project.zip)

And here is a hotfix for the grid content issue:
`com.giphy.sdk:ui:2.0.1-hotfix`

Please let me know if that works for you.

**Comment by colorgold** [comment] 2020-09-14 22:46
@ALexanderLonsky I was using the same instance of the dialog. I followed your example and it worked. Thank you so much for your help.

**Closed** 2020-09-15 08:06 UTC
